# Generated by Django 4.0.4 on 2022-05-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='inventory',
        ),
        migrations.DeleteModel(
            name='manager',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='stocks',
        ),
    ]
