# Generated by Django 4.0.4 on 2022-05-12 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('inventory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=15)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
        ),
    ]
