# Generated by Django 4.0.4 on 2022-05-12 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_inventory_manager_id_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('stock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=20)),
                ('available_quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
