# Generated by Django 4.0.4 on 2022-05-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='price',
            new_name='price_per_kg',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='quantity',
            new_name='quantity_in_kg',
        ),
    ]
