# Generated by Django 4.0.4 on 2022-05-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('manager', '0001_initial'),
        ('sales', '0002_rename_price_sales_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager'),
        ),
    ]
