# Generated by Django 4.0.4 on 2022-05-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sales_customer_id_alter_sales_manager_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='manager_id',
        ),
    ]
