# Generated by Django 4.0.4 on 2022-05-12 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('farmer', '0002_remove_product_farmer_id_remove_product_manager_id_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager'),
        ),
        migrations.DeleteModel(
            name='farmer',
        ),
        migrations.DeleteModel(
            name='inventory',
        ),
        migrations.DeleteModel(
            name='manager',
        ),
        migrations.DeleteModel(
            name='stocks',
        ),
    ]
