# Generated by Django 4.0.4 on 2022-05-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_no', models.PositiveBigIntegerField()),
                ('department', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
